title: Zhe Zhang | 张喆
url: "https://ankitsultana.com"
<<<<<<< HEAD
baseurl: "/cv"
=======
baseurl: "/cv-gh-pages"
>>>>>>> c45f0f70170351eba92686ff5db21815a65f5ca9

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/paranoid2droid"
footer_text: "The best you can is good enough."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/cv/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "paranoid2droid@gmail.com"
