title: Zhe Zhang | 张喆
url: "https://zhezhang.me/"
baseurl: "/cv"


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "zhezhang.me"
footer_text: "The best you can is good enough."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Main"
   link: "/"
 - name: "Resume(PDF)"
   link: "resume_zhezhang.pdf"
 - name: "Contact"
   link: "contact"
