title: Zhe Zhang | 张喆
url: "https://paranoid2droid.github.io/"
baseurl: "/cv"


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/paranoid2droid"
footer_text: "The best you can is good enough."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Main"
   link: "/"
 - name: "PDF"
   link: "resume.pdf"
 - name: "Contact"
   link: "/contact/"
